services:
  - type: web
    name: silent-speak
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --pythonpath 'silent_speak - Copy' silent_speak.wsgi
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
